package com.bureau.utils

/**
 * Created by Abhin.
 */

const val KEY_NUMBER = "number"

val MY_PERMISSIONS_REQUEST_READ_CALL_LOG = 0
val MY_PERMISSIONS_REQUEST_READ_PHONE_STATE = 1
val MY_PERMISSIONS_REQUEST_PROCESS_OUTGOING_CALLS = 2